services:
  # ---------- DATABASES ----------
  postgres-user:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_DB: UserDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sebi1404
    ports:
      - "5432:5432"
    volumes:
      - pgdata-user:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres-device:
    image: postgres:latest
    container_name: postgres-device
    environment:
      POSTGRES_DB: DeviceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sebi1404
    ports:
      - "5433:5432"  # separate host port for second DB
    volumes:
      - pgdata-device:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres-credential:
    image: postgres:latest
    container_name: postgres-credential
    environment:
      POSTGRES_DB: CredentialDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sebi1404
    ports:
      - "5434:5432"  # separate host port for credential DB
    volumes:
      - pgdata-credential:/var/lib/postgresql/data
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: NiGgZ-9bS_2eYh1QpU6V2A
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka/kraft/server.properties:/opt/kafka/config/kraft/server.properties:ro
    networks:
      - proxy-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    # One-time format if needed, then start the broker
    command: >
      bash -lc '
        set -e
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          /opt/kafka/bin/kafka-storage.sh format \
            -t "$$(/opt/kafka/bin/kafka-storage.sh random-uuid)" \
            -c /opt/kafka/config/kraft/server.properties
        fi
        exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      '

  # ---------- USER SERVICE ----------
  user-service:
    build:
      context: ./UserManagement
    container_name: user-service
    depends_on:
      postgres-user:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/UserDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sebi1404
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - proxy-network

  # ---------- DEVICE SERVICE ----------
  device-service:
    build:
      context: ./DeviceManagement
    container_name: device-service
    depends_on:
      postgres-device:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-device:5432/DeviceDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sebi1404
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - proxy-network


  authorization-service:
    build:
      context: ./Authorization
    container_name: authorization-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-credential:5432/CredentialDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sebi1404
      JWT_SECRET: "d6f1b5c1c91f4b93b77b59fef9d9d56d4cb6abeb4f2769d7f3d6df6efb2d8a4b"
    depends_on:
      postgres-credential:
        condition: service_healthy
    networks:
      - proxy-network



  web:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api/users
        VITE_DEVICE_API_URL: /api/devices
    container_name: web
    depends_on:
      user-service:
        condition: service_started
      device-service:
        condition: service_started
    networks:
      - proxy-network

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80" # The HTTP port
      # - "443:443" # The HTTPS port
      - "8080:8080" # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
#    develop: # Enable live reload of dynamic configuration files on Windows, if using Unix based system needs to be commented out
#      watch:
#        - path: ./dynamic                   # watch the whole folder
#          action: restart
    networks:
      - proxy-network


volumes:
  pgdata-user:
  pgdata-device:
  pgdata-credential:
  kafka-data:


# Define a shared network for all services
networks:
  proxy-network:
    driver: bridge
